# Generated by Django 5.0.4 on 2024-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='customer_images/'),
        ),
        migrations.AlterField(
            model_name='picsposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics_posts/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='seller_images/'),
        ),
    ]
