# Generated by Django 5.0.4 on 2024-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customerprofile_image_alter_picsposts_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picsposts',
            name='service',
        ),
        migrations.AddField(
            model_name='picsposts',
            name='service_type',
            field=models.TextField(default='General'),
            preserve_default=False,
        ),
    ]
