# Generated by Django 5.0.4 on 2024-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_picsposts_service_picsposts_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.TextField(),
        ),
    ]
