# Generated by Django 5.0.4 on 2024-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_service_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='desc',
        ),
    ]
